#define ERR_E2BIG         "Argument list too long"
#define ERR_ACCES         "Permission denied"
#define ERR_ADDRINUSE     "Address already in use"
#define ERR_ADDRNOTAVAIL  "Address not available"
#define ERR_AFNOSUPPORT   "Address family not supported"
#define ERR_AGAIN         "Resource  temporarily  unavailable"
#define ERR_ALREADY       "Connection already in progress"
#define ERR_BADE          "Invalid exchange"
#define ERR_BADF          "Bad file descriptor"
#define ERR_BADFD         "File descriptor in bad state"
#define ERR_BADMSG        "Bad message"
#define ERR_BADR          "Invalid request descriptor"
#define ERR_BADRQC        "Invalid request code"
#define ERR_BADSLT        "Invalid slot"
#define ERR_BUSY          "Device or resource busy"
#define ERR_CANCELED      "Operation canceled"
#define ERR_CHILD         "No child processes"
#define ERR_CHRNG         "Channel number out of range"
#define ERR_COMM          "Communication error on send"
#define ERR_CONNABORTED   "Connection aborted"
#define ERR_CONNREFUSED   "Connection refused"
#define ERR_CONNRESET     "Connection reset"
#define ERR_DEADLK        "Resource deadlock avoided"
#define ERR_DESTADDRREQ   "Destination address required"
#define ERR_DOM           "Mathematics argument out of domain of function"
#define ERR_DQUOT         "Disk quota exceeded"
#define ERR_EXIST         "File exists"
#define ERR_FAULT         "Bad address"
#define ERR_FBIG          "File too large"
#define ERR_HOSTDOWN      "Host is down"
#define ERR_HOSTUNREACH   "Host is unreachable"
#define ERR_IDRM          "Identifier removed"
#define ERR_ILSEQ         "Illegal byte sequence"
#define ERR_INPROGRESS    "Operation in progress"
#define ERR_INTR          "Interrupted function call"
#define ERR_INVAL         "Invalid argument"
#define ERR_IO            "Input/Output error"
#define ERR_ISCONN        "Socket is connected"
#define ERR_ISDIR         "Is a directory"
#define ERR_KEYEXPIRED    "Key has expired"
#define ERR_KEYREJECTED   "Key was rejected by service"
#define ERR_KEYREVOKED    "Key has been revoked"
#define ERR_MSGSIZE       "Message too long"
#define ERR_NETDOWN       "Network is down"
#define ERR_NETRESET      "Connection aborted by network"
#define ERR_NETUNREACH    "Network unreachable"
#define ERR_NODATA        "No message is available on the STREAM head read queue"
#define ERR_NOKEY         "Required key not available"
#define ERR_NOMSG         "No message of the desired type"
#define ERR_NOPROTOOPT    "Protocol not available"
#define ERR_NOSR          "No STREAM resources"
#define ERR_NOSTR         "Not a STREAM"
#define ERR_NOTCONN       "The socket is not connected"
#define ERR_NOTSOCK       "Not a socket"
